### ISSUE TITLE
Crash of 64 iOS app at Foundation.log("%@", ...) on device

### ISSUE THREAD

**Issue by titovmaxim** [robovm/robovm#748]
The 64 bit IPA build crashes with latest nigthlies of libGDX and roboVM on the device. The test device is iPhone 5s, firmware: 8.1.3 (12B466). libGDX & roboVM are the latest nightly (08.02.2015). The issue was first opened here (#737), than in libGDX tracker (#2800), than again here.

The simple tests showed that crash occurs during logging by Foundation.log("%@", ...). However Foundation.log(...) without format string works just fine.

I have done some simple tests with an empty app with test logging at the very beginning of the launcher:

<pre><code>@Override
protected IOSApplication createApplication()
{
	Foundation.log("BEGIN");
	Foundation.log("%@", new NSString("test1"));
	Foundation.log("END");
	...
}
</code></pre>

This code works fine when compiled to 32 bit IPA. However, it DOES CRASH at the second logging line (with "%@") when compiled to 64 bit IPA. First logging without formatting string works. Here is the logging output (The complete crash dump is in the next message):

<pre><code>Ted the Jumper[557] <Warning>: ==================== BEGIN
ReportCrash[558] <Error>: task_set_exception_ports(B07, 400, D03, 0, 0) failed with error (4: (os/kern) invalid argument)
ReportCrash[558] <Notice>: ReportCrash acting against PID 557
ReportCrash[558] <Notice>: Formulating crash report for process Ted the Jumper[557]
com.apple.xpc.launchd[1] (UIKitApplication:com.mmxgames.ttj.ios[0x932d][557]) <Notice>: Service exited due to signal: Segmentation fault: 11
ReportCrash[558] <Notice>: Saved report to /var/mobile/Library/Logs/CrashReporter/Ted the Jumper_2015-02-08-152601_iPhone-Maxim-Titov.ips
SpringBoard[49] <Warning>: Application 'UIKitApplication:com.mmxgames.ttj.ios[0x932d]' crashed.
</code></pre>

As a last test I have disabled the logging in my app at the early step like this:
<pre><code>@Override
protected IOSApplication createApplication()
{
	...
	final IOSApplication app = new IOSApplication(Game.instance, cfg);
	app.setLogLevel(Application.LOG_NONE);
	return app;
}
</code></pre>

And now it also works in both 32 & 64 bit IPAs (but without logging).

**Comment by titovmaxim** [comment]
Complete crash dump (symbolication does not work properly, but there is nothing to symbolicate anyway - it is a direct call to Foundation.log):

<pre><code>
Incident Identifier: E3BB2CAD-91CE-4B31-96A9-15A43EEE1343
CrashReporter Key:   3f2c8822df225a696a48c539965873727a352c02
Hardware Model:      iPhone6,2
Process:             Ted the Jumper [557]
Path:                /private/var/mobile/Containers/Bundle/Application/19B22012-0F88-4CE1-A864-ECD230A4EF46/Ted the Jumper.app/Ted the Jumper
Identifier:          com.mmxgames.ttj.ios
Version:             1.2.1171 (1.2.0)
Code Type:           ARM-64 (Native)
Parent Process:      launchd [1]

Date/Time:           2015-02-08 15:26:01.818 +0700
Launch Time:         2015-02-08 15:26:01.241 +0700
OS Version:          iOS 8.1.3 (12B466)
Report Version:      105

Exception Type:  EXC_CRASH (SIGSEGV)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Triggered by Thread:  1

Thread 0 name:  Dispatch queue: com.apple.main-thread
Thread 0:
0   libobjc.A.dylib               	0x0000000198593bdc objc_msgSend + 28
1   Foundation                    	0x0000000188d4ba74 _NSDescriptionWithStringProxyFunc + 68
2   CoreFoundation                	0x0000000187e445f4 __CFStringAppendFormatCore + 6948
3   CoreFoundation                	0x0000000187e42a94 _CFStringCreateWithFormatAndArgumentsAux2 + 244
4   CoreFoundation                	0x0000000187e5fd48 _CFLogvEx2 + 148
5   Foundation                    	0x0000000188c6b93c NSLogv + 104
6   Foundation                    	0x0000000188c6b8c4 NSLog + 20
7   Ted the Jumper                	0x000000010094500c 0x100028000 + 9555980
8   Ted the Jumper                	0x00000001009450e8 0x100028000 + 9556200
9   Ted the Jumper                	0x0000000100599d94 0x100028000 + 5709204
10  Ted the Jumper                	0x0000000100443f68 0x100028000 + 4308840
11  Ted the Jumper                	0x0000000100bebe84 0x100028000 + 12336772
12  Ted the Jumper                	0x0000000100bebf74 0x100028000 + 12337012
13  UIKit                         	0x000000018c69a6ec -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 300
14  UIKit                         	0x000000018c8b1684 -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] + 2280
15  UIKit                         	0x000000018c8b3e04 -[UIApplication _runWithMainScene:transitionContext:completion:] + 1476
16  UIKit                         	0x000000018c8b249c -[UIApplication workspaceDidEndTransaction:] + 180
17  FrontBoardServices            	0x00000001900e9628 __31-[FBSSerialQueue performAsync:]_block_invoke + 24
18  CoreFoundation                	0x0000000187e32a24 __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 16
19  CoreFoundation                	0x0000000187e31b2c __CFRunLoopDoBlocks + 308
20  CoreFoundation                	0x0000000187e2fd2c __CFRunLoopRun + 692
21  CoreFoundation                	0x0000000187d5d0a0 CFRunLoopRunSpecific + 392
22  UIKit                         	0x000000018c693aa8 -[UIApplication _run] + 548
23  UIKit                         	0x000000018c68eaa0 UIApplicationMain + 1484
24  Ted the Jumper                	0x0000000100bd6410 0x100028000 + 12248080
25  Ted the Jumper                	0x0000000100bd5588 0x100028000 + 12244360
26  Ted the Jumper                	0x0000000100bd55f4 0x100028000 + 12244468
27  Ted the Jumper                	0x0000000100599f10 0x100028000 + 5709584
28  Ted the Jumper                	0x0000000100e75840 0x100028000 + 14997568
29  Ted the Jumper                	0x0000000100e6b748 0x100028000 + 14956360
30  Ted the Jumper                	0x0000000100e6e208 0x100028000 + 14967304
31  Ted the Jumper                	0x0000000100e6e29c 0x100028000 + 14967452
32  Ted the Jumper                	0x0000000100e65f24 0x100028000 + 14933796
33  Ted the Jumper                	0x0000000100e5b7f0 0x100028000 + 14890992
34  libdyld.dylib                 	0x0000000198beea04 start + 0

Thread 1 Crashed:
0   libsystem_kernel.dylib        	0x0000000198d07078 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	0x0000000198da2fe0 _pthread_cond_wait + 620
2   Ted the Jumper                	0x0000000100e8e098 0x100028000 + 15098008
3   Ted the Jumper                	0x0000000100e84d3c 0x100028000 + 15060284
4   Ted the Jumper                	0x0000000100e8c3c8 0x100028000 + 15090632
5   libsystem_pthread.dylib       	0x0000000198da3e7c _pthread_body + 160
6   libsystem_pthread.dylib       	0x0000000198da3dd8 _pthread_start + 156
7   libsystem_pthread.dylib       	0x0000000198da0fac thread_start + 0

Thread 2 name:  Dispatch queue: com.apple.libdispatch-manager
Thread 2:
0   libsystem_kernel.dylib        	0x0000000198cecc94 kevent64 + 8
1   libdispatch.dylib             	0x0000000198bd497c _dispatch_mgr_invoke + 272
2   libdispatch.dylib             	0x0000000198bc73b0 _dispatch_mgr_thread + 48

Thread 3:
0   libsystem_kernel.dylib        	0x0000000198d07c78 __workq_kernreturn + 8
1   libsystem_pthread.dylib       	0x0000000198da1390 _pthread_wqthread + 988
2   libsystem_pthread.dylib       	0x0000000198da0fa4 start_wqthread + 0

Thread 4:
0   libsystem_kernel.dylib        	0x0000000198d07c78 __workq_kernreturn + 8
1   libsystem_pthread.dylib       	0x0000000198da1390 _pthread_wqthread + 988
2   libsystem_pthread.dylib       	0x0000000198da0fa4 start_wqthread + 0

Thread 5:
0   libsystem_kernel.dylib        	0x0000000198d07078 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	0x0000000198da2fe0 _pthread_cond_wait + 620
2   Ted the Jumper                	0x0000000100e6fd5c 0x100028000 + 14974300
3   Ted the Jumper                	0x0000000100658508 0x100028000 + 6489352
4   Ted the Jumper                	0x00000001006584a0 0x100028000 + 6489248
5   Ted the Jumper                	0x000000010064aedc 0x100028000 + 6434524
6   Ted the Jumper                	0x0000000100673d00 0x100028000 + 6601984
7   Ted the Jumper                	0x0000000100e75840 0x100028000 + 14997568
8   Ted the Jumper                	0x0000000100e6b748 0x100028000 + 14956360
9   Ted the Jumper                	0x0000000100e6b2b4 0x100028000 + 14955188
10  Ted the Jumper                	0x0000000100e74db4 0x100028000 + 14994868
11  Ted the Jumper                	0x0000000100e8c16c 0x100028000 + 15090028
12  Ted the Jumper                	0x0000000100e88b64 0x100028000 + 15076196
13  Ted the Jumper                	0x0000000100e8d9a0 0x100028000 + 15096224
14  libsystem_pthread.dylib       	0x0000000198da3e7c _pthread_body + 160
15  libsystem_pthread.dylib       	0x0000000198da3dd8 _pthread_start + 156
16  libsystem_pthread.dylib       	0x0000000198da0fac thread_start + 0

Thread 6:
0   libsystem_kernel.dylib        	0x0000000198d07078 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	0x0000000198da2fe0 _pthread_cond_wait + 620
2   Ted the Jumper                	0x0000000100e6fd5c 0x100028000 + 14974300
3   Ted the Jumper                	0x0000000100658508 0x100028000 + 6489352
4   Ted the Jumper                	0x00000001006584c0 0x100028000 + 6489280
5   Ted the Jumper                	0x000000010067fa10 0x100028000 + 6650384
6   Ted the Jumper                	0x000000010067fbf0 0x100028000 + 6650864
7   Ted the Jumper                	0x000000010067f980 0x100028000 + 6650240
8   Ted the Jumper                	0x000000010064a1c0 0x100028000 + 6431168
9   Ted the Jumper                	0x0000000100673d00 0x100028000 + 6601984
10  Ted the Jumper                	0x0000000100e75840 0x100028000 + 14997568
11  Ted the Jumper                	0x0000000100e6b748 0x100028000 + 14956360
12  Ted the Jumper                	0x0000000100e6b2b4 0x100028000 + 14955188
13  Ted the Jumper                	0x0000000100e74db4 0x100028000 + 14994868
14  Ted the Jumper                	0x0000000100e8c16c 0x100028000 + 15090028
15  Ted the Jumper                	0x0000000100e88b64 0x100028000 + 15076196
16  Ted the Jumper                	0x0000000100e8d9a0 0x100028000 + 15096224
17  libsystem_pthread.dylib       	0x0000000198da3e7c _pthread_body + 160
18  libsystem_pthread.dylib       	0x0000000198da3dd8 _pthread_start + 156
19  libsystem_pthread.dylib       	0x0000000198da0fac thread_start + 0

Thread 7:
0   libsystem_kernel.dylib        	0x0000000198d07078 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	0x0000000198da2fe0 _pthread_cond_wait + 620
2   Ted the Jumper                	0x0000000100e6fd5c 0x100028000 + 14974300
3   Ted the Jumper                	0x0000000100658508 0x100028000 + 6489352
4   Ted the Jumper                	0x00000001006584a0 0x100028000 + 6489248
5   Ted the Jumper                	0x000000010064a898 0x100028000 + 6432920
6   Ted the Jumper                	0x000000010064a6c8 0x100028000 + 6432456
7   Ted the Jumper                	0x0000000100673d00 0x100028000 + 6601984
8   Ted the Jumper                	0x0000000100e75840 0x100028000 + 14997568
9   Ted the Jumper                	0x0000000100e6b748 0x100028000 + 14956360
10  Ted the Jumper                	0x0000000100e6b2b4 0x100028000 + 14955188
11  Ted the Jumper                	0x0000000100e74db4 0x100028000 + 14994868
12  Ted the Jumper                	0x0000000100e8c16c 0x100028000 + 15090028
13  Ted the Jumper                	0x0000000100e88b64 0x100028000 + 15076196
14  Ted the Jumper                	0x0000000100e8d9a0 0x100028000 + 15096224
15  libsystem_pthread.dylib       	0x0000000198da3e7c _pthread_body + 160
16  libsystem_pthread.dylib       	0x0000000198da3dd8 _pthread_start + 156
17  libsystem_pthread.dylib       	0x0000000198da0fac thread_start + 0

Thread 8:
0   libsystem_kernel.dylib        	0x0000000198d07c78 __workq_kernreturn + 8
1   libsystem_pthread.dylib       	0x0000000198da1390 _pthread_wqthread + 988
2   libsystem_pthread.dylib       	0x0000000198da0fa4 start_wqthread + 0

Thread 1 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000104   x1: 0x0000000000000000   x2: 0x0000000000000900   x3: 0x0000000000000000
    x4: 0x0000000000000000   x5: 0x0000000000000060   x6: 0x0000000000000000   x7: 0x0000000000000000
    x8: 0x0000000101f87df0   x9: 0x0000000000000000  x10: 0x0000000000060f00  x11: 0x0000000000060f00
   x12: 0x000000007fffff80  x13: 0x0000000000000000  x14: 0x000000010438c43a  x15: 0x0000000000001000
   x16: 0x0000000000000131  x17: 0x0000000000000000  x18: 0x0000000000000000  x19: 0x0000000101cbad30
   x20: 0x0000000101cbada0  x21: 0x0000000000000001  x22: 0x0000000101cbadc0  x23: 0x0000000000000000
   x24: 0x0000000000000900  x25: 0x0000000101f98000  x26: 0x0000000000000901  x27: 0x0000000000000a00
   x28: 0x0000000101cbadbc  fp: 0x0000000101f87e80   lr: 0x0000000198da2fe4
    sp: 0x0000000101f87de0   pc: 0x0000000198d07078 cpsr: 0x60000000

Binary Images:
0x100028000 - 0x101577fff Ted the Jumper arm64  <590622d7a59e34b09da8ddb6cf6b6a48> /var/mobile/Containers/Bundle/Application/19B22012-0F88-4CE1-A864-ECD230A4EF46/Ted the Jumper.app/Ted the Jumper
0x120078000 - 0x12009ffff dyld arm64  <21c893f791653e989e1c3e15446d772b> /usr/lib/dyld
0x186654000 - 0x1867e7fff AVFoundation arm64  <c9cd60a62cfb3e77be72db6cd3062a09> /System/Library/Frameworks/AVFoundation.framework/AVFoundation
0x1867e8000 - 0x18684cfff libAVFAudio.dylib arm64  <017d90360b443ae788ef31cfd73d17f6> /System/Library/Frameworks/AVFoundation.framework/libAVFAudio.dylib
0x186890000 - 0x186890fff Accelerate arm64  <e9ba7838f51634a7b59ed392be50e86f> /System/Library/Frameworks/Accelerate.framework/Accelerate
0x1868a8000 - 0x186ac7fff vImage arm64  <da44067fc79931c7aef1b7e88bf82a83> /System/Library/Frameworks/Accelerate.framework/Frameworks/vImage.framework/vImage
0x186ac8000 - 0x186b6ffff libBLAS.dylib arm64  <e5276e7784ef34a4baca480264978ea0> /System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/libBLAS.dylib
0x186b70000 - 0x186eeafff libLAPACK.dylib arm64  <165b05f9f75736d5ae8f5f39293bd6e7> /System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/libLAPACK.dylib
0x186eec000 - 0x186f01fff libLinearAlgebra.dylib arm64  <5574ec3bd4e537e1b662d38a63aec58b> /System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/libLinearAlgebra.dylib
0x186f04000 - 0x186f6cfff libvDSP.dylib arm64  <004f5668574139bc906c5fa4fdced3b1> /System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/libvDSP.dylib
0x186f70000 - 0x186f93fff libvMisc.dylib arm64  <5790e7ace143367ea6f2428852be384e> /System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/libvMisc.dylib
0x186f94000 - 0x186f94fff vecLib arm64  <211d7711a6e93fe8ae6d6b42585cad2d> /System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/vecLib
0x186f98000 - 0x186fc6fff Accounts arm64  <2508d336b9893176ad4e1bc67ff04188> /System/Library/Frameworks/Accounts.framework/Accounts
0x186fc8000 - 0x186fc8fff AdSupport arm64  <977faefc983d3d72ad5e531740e4130a> /System/Library/Frameworks/AdSupport.framework/AdSupport
0x186fcc000 - 0x18704efff AddressBook arm64  <09e2e24ef5e23fb8a62ae209466a64bd> /System/Library/Frameworks/AddressBook.framework/AddressBook
0x187050000 - 0x1871a0fff AddressBookUI arm64  <e79239b432af33e783296d2a9841578e> /System/Library/Frameworks/AddressBookUI.framework/AddressBookUI
0x187368000 - 0x187625fff AudioToolbox arm64  <f0b739a395993b808d66e85e1a6e9f18> /System/Library/Frameworks/AudioToolbox.framework/AudioToolbox
0x1877c4000 - 0x1879cffff CFNetwork arm64  <68adcebf440d30769bd2d67adc7932a2> /System/Library/Frameworks/CFNetwork.framework/CFNetwork
0x1879d0000 - 0x187a67fff CloudKit arm64  <8f226c83b2793a0db1eefa14d697c04b> /System/Library/Frameworks/CloudKit.framework/CloudKit
0x187a68000 - 0x187acdfff CoreAudio arm64  <10aae62ba1c43dd29bc678fbf0f985ef> /System/Library/Frameworks/CoreAudio.framework/CoreAudio
0x187af0000 - 0x187b11fff CoreBluetooth arm64  <b30de1ce792a318aa125a84b06e8a95d> /System/Library/Frameworks/CoreBluetooth.framework/CoreBluetooth
0x187b14000 - 0x187d52fff CoreData arm64  <33c0d795a45e35c9affed5cf9d83a8a1> /System/Library/Frameworks/CoreData.framework/CoreData
0x187d54000 - 0x1880b0fff CoreFoundation arm64  <83a9627362333366a8543e8c2d28166e> /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
0x1880b4000 - 0x188216fff CoreGraphics arm64  <7a02a2d0b69f3706b3cb91726db6f8af> /System/Library/Frameworks/CoreGraphics.framework/CoreGraphics
0x188490000 - 0x1885bdfff CoreImage arm64  <444c44b06f533bad9c1b030edd486b49> /System/Library/Frameworks/CoreImage.framework/CoreImage
0x1885c0000 - 0x18861dfff CoreLocation arm64  <6fd7bd8116a63a8fafda547c6380a19b> /System/Library/Frameworks/CoreLocation.framework/CoreLocation
0x188658000 - 0x188716fff CoreMedia arm64  <f090b302cad23151b3aef050d50be152> /System/Library/Frameworks/CoreMedia.framework/CoreMedia
0x188718000 - 0x1887e6fff CoreMotion arm64  <0b3890116c60302980d4c0c3a0c14453> /System/Library/Frameworks/CoreMotion.framework/CoreMotion
0x1887e8000 - 0x188859fff CoreTelephony arm64  <f99cf601387938d3808c32e97a9a30cf> /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
0x18885c000 - 0x18895efff CoreText arm64  <e46b1730715c339a82db3f67eee4fe84> /System/Library/Frameworks/CoreText.framework/CoreText
0x188960000 - 0x18897cfff CoreVideo arm64  <402f868dbba63d59a3b2e738982b9d71> /System/Library/Frameworks/CoreVideo.framework/CoreVideo
0x188980000 - 0x188aa4fff EventKit arm64  <15cacaa609e33790a3bc644eb4d92191> /System/Library/Frameworks/EventKit.framework/EventKit
0x188c58000 - 0x188eacfff Foundation arm64  <e596bd80bcc83f15aca36a7ef014f457> /System/Library/Frameworks/Foundation.framework/Foundation
0x188eb0000 - 0x188edbfff GLKit arm64  <d97cb7e7881e31abadb27182d86bac74> /System/Library/Frameworks/GLKit.framework/GLKit
0x188edc000 - 0x188f05fff GSS arm64  <6552f84a5add33b9a01d1e278d4ebd88> /System/Library/Frameworks/GSS.framework/GSS
0x188f1c000 - 0x188f1cfff GameKit arm64  <fa6096a22bdd36cea421b70a9833212f> /System/Library/Frameworks/GameKit.framework/GameKit
0x188fc4000 - 0x189030fff IOKit arm64  <1cd3da5151d03be5a0ba0c30c19228ea> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
0x189034000 - 0x1892cefff ImageIO arm64  <10491d236e813eb6bb07d792047a7475> /System/Library/Frameworks/ImageIO.framework/ImageIO
0x1892d0000 - 0x189770fff JavaScriptCore arm64  <9d8bd2cbb97c33c59376cf656634704a> /System/Library/Frameworks/JavaScriptCore.framework/JavaScriptCore
0x189fe4000 - 0x189feafff MediaAccessibility arm64  <5dc0d8bda3593b9cb00a8703b21953fd> /System/Library/Frameworks/MediaAccessibility.framework/MediaAccessibility
0x189fec000 - 0x18a207fff MediaPlayer arm64  <526279b5f7a9316ea187338519f6d8b6> /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
0x18a208000 - 0x18a622fff MediaToolbox arm64  <dbda28de74cd3fcca10622bbf00809b9> /System/Library/Frameworks/MediaToolbox.framework/MediaToolbox
0x18a624000 - 0x18a6f7fff MessageUI arm64  <f307aec0262838e1ad1302805c8a025c> /System/Library/Frameworks/MessageUI.framework/MessageUI
0x18a6f8000 - 0x18a76bfff Metal arm64  <69e3d92ae3ec3375a550022b7ac4a184> /System/Library/Frameworks/Metal.framework/Metal
0x18a76c000 - 0x18a818fff MobileCoreServices arm64  <21a27692c6393c00a8f8f2bbd3ccb23c> /System/Library/Frameworks/MobileCoreServices.framework/MobileCoreServices
0x18a93c000 - 0x18a971fff OpenAL arm64  <1bbe9dd773463d5c93a368ff87097ed4> /System/Library/Frameworks/OpenAL.framework/OpenAL
0x18b99c000 - 0x18b9a6fff OpenGLES arm64  <b707e102e4553f26994bfef0579c9f52> /System/Library/Frameworks/OpenGLES.framework/OpenGLES
0x18b9ac000 - 0x18b9adfff libCVMSPluginSupport.dylib arm64  <7e1f08d7776b37efb6ff01f6486afcde> /System/Library/Frameworks/OpenGLES.framework/libCVMSPluginSupport.dylib
0x18b9b0000 - 0x18b9b3fff libCoreFSCache.dylib arm64  <5888d3587c633af2ac7cf57ac15ab5e4> /System/Library/Frameworks/OpenGLES.framework/libCoreFSCache.dylib
0x18b9b4000 - 0x18b9b8fff libCoreVMClient.dylib arm64  <291806c545fe3219b844a93e2fb682b4> /System/Library/Frameworks/OpenGLES.framework/libCoreVMClient.dylib
0x18b9bc000 - 0x18b9c6fff libGFXShared.dylib arm64  <f5e5cfc1d6673d469f25b3fa77fa995b> /System/Library/Frameworks/OpenGLES.framework/libGFXShared.dylib
0x18b9c8000 - 0x18ba13fff libGLImage.dylib arm64  <4e284cf07fe23789b94c9f204f7aa52e> /System/Library/Frameworks/OpenGLES.framework/libGLImage.dylib
0x18bf70000 - 0x18c0f4fff QuartzCore arm64  <313aba56d17e30d1b68b2fdfda1820f8> /System/Library/Frameworks/QuartzCore.framework/QuartzCore
0x18c0f8000 - 0x18c153fff QuickLook arm64  <ae12a3ed0acf3b6ca816e95d4a894d70> /System/Library/Frameworks/QuickLook.framework/QuickLook
0x18c388000 - 0x18c3dafff Security arm64  <cb64d037f82a3f0a92ab63708334c938> /System/Library/Frameworks/Security.framework/Security
0x18c584000 - 0x18c59cfff StoreKit arm64  <e7adbf448a9839529a876e42b9293a44> /System/Library/Frameworks/StoreKit.framework/StoreKit
0x18c5a0000 - 0x18c613fff SystemConfiguration arm64  <cbcb5237ab8637aebf0cb493aaa4af92> /System/Library/Frameworks/SystemConfiguration.framework/SystemConfiguration
0x18c618000 - 0x18cf8dfff UIKit arm64  <a1283daa6f5a33048ab9d29d91f62c09> /System/Library/Frameworks/UIKit.framework/UIKit
0x18cf90000 - 0x18d009fff VideoToolbox arm64  <13a05b41cd0136239ef94de508febe1d> /System/Library/Frameworks/VideoToolbox.framework/VideoToolbox
0x18d00c000 - 0x18d26afff WebKit arm64  <a4d29b7cd5073edd9ae6a7b476421caa> /System/Library/Frameworks/WebKit.framework/WebKit
0x18d69c000 - 0x18d6a9fff AOSNotification arm64  <8b9793a334fa3013803a6cb713053b44> /System/Library/PrivateFrameworks/AOSNotification.framework/AOSNotification
0x18d834000 - 0x18d88cfff AccountsDaemon arm64  <84c862ef63b332eb81b98f5ab414e3f4> /System/Library/PrivateFrameworks/AccountsDaemon.framework/AccountsDaemon
0x18d890000 - 0x18d8b6fff AccountsUI arm64  <a7d2776eb1ad39d887a5e62c0292e597> /System/Library/PrivateFrameworks/AccountsUI.framework/AccountsUI
0x18d8b8000 - 0x18d8bdfff AggregateDictionary arm64  <2f9120e6400835f08bd7bfd2d4ada020> /System/Library/PrivateFrameworks/AggregateDictionary.framework/AggregateDictionary
0x18dabc000 - 0x18daf0fff AirPlaySupport arm64  <442269677a2e302ea3bf68c54f1ff539> /System/Library/PrivateFrameworks/AirPlaySupport.framework/AirPlaySupport
0x18dd3c000 - 0x18dd86fff AppSupport arm64  <f35ee13bec64354d9044e2a5ea519640> /System/Library/PrivateFrameworks/AppSupport.framework/AppSupport
0x18dd88000 - 0x18dddbfff AppleAccount arm64  <267a2b98738333f099ccb095820590d6> /System/Library/PrivateFrameworks/AppleAccount.framework/AppleAccount
0x18dddc000 - 0x18de1dfff AppleAccountUI arm64  <9a5d09bbd28737fa9b13882f25624c42> /System/Library/PrivateFrameworks/AppleAccountUI.framework/AppleAccountUI
0x18dee4000 - 0x18df2cfff AppleJPEG arm64  <8377453201ad3862b7b6182be4ac4342> /System/Library/PrivateFrameworks/AppleJPEG.framework/AppleJPEG
0x18df40000 - 0x18df54fff ApplePushService arm64  <fc28105486c5380f95f8d52a3a3c2fac> /System/Library/PrivateFrameworks/ApplePushService.framework/ApplePushService
0x18df58000 - 0x18df61fff AppleSRP arm64  <7a5d169c15b83573a29f1c018c8ecbb8> /System/Library/PrivateFrameworks/AppleSRP.framework/AppleSRP
0x18df74000 - 0x18df7ffff AssertionServices arm64  <52d911832bf9382d802961ea9d1614f9> /System/Library/PrivateFrameworks/AssertionServices.framework/AssertionServices
0x18df80000 - 0x18df9bfff AssetsLibraryServices arm64  <1b0a20bfd23a3295aec6d82c8b7a2f24> /System/Library/PrivateFrameworks/AssetsLibraryServices.framework/AssetsLibraryServices
0x18df9c000 - 0x18dfc6fff AssistantServices arm64  <0126e5fa902232cbb4cfbcb39f3a6b9e> /System/Library/PrivateFrameworks/AssistantServices.framework/AssistantServices
0x18e000000 - 0x18e004fff BTLEAudioController arm64  <8539b6078e1b3c739d412842418188ed> /System/Library/PrivateFrameworks/BTLEAudioController.framework/BTLEAudioController
0x18e008000 - 0x18e024fff BackBoardServices arm64  <62bf606fae3b3231b48d5ec35a552aa5> /System/Library/PrivateFrameworks/BackBoardServices.framework/BackBoardServices
0x18e02c000 - 0x18e069fff BaseBoard arm64  <62044bafc2293567aec7797b25708b48> /System/Library/PrivateFrameworks/BaseBoard.framework/BaseBoard
0x18e084000 - 0x18e08bfff BluetoothManager arm64  <afd2bca7997434f08d4723c3005ca0f9> /System/Library/PrivateFrameworks/BluetoothManager.framework/BluetoothManager
0x18e08c000 - 0x18e0bcfff Bom arm64  <2724021b087139bcaa636d640e9b4127> /System/Library/PrivateFrameworks/Bom.framework/Bom
0x18e1b4000 - 0x18e1e4fff CalendarFoundation arm64  <210e5342ce603b9887f0e10131df34a4> /System/Library/PrivateFrameworks/CalendarFoundation.framework/CalendarFoundation
0x18e31c000 - 0x18e326fff CaptiveNetwork arm64  <8ba9d547383b3a7fba9a31cc361fc06a> /System/Library/PrivateFrameworks/CaptiveNetwork.framework/CaptiveNetwork
0x18e328000 - 0x18e472fff Celestial arm64  <48f92eb00d0636808c583028f766d983> /System/Library/PrivateFrameworks/Celestial.framework/Celestial
0x18e484000 - 0x18e49ffff CertInfo arm64  <34bb9442ee1633238c1830d4ba2e7103> /System/Library/PrivateFrameworks/CertInfo.framework/CertInfo
0x18e4a0000 - 0x18e4a6fff CertUI arm64  <d540e6a6a1ab3b119b88d31509a2f390> /System/Library/PrivateFrameworks/CertUI.framework/CertUI
0x18e5f0000 - 0x18e614fff ChunkingLibrary arm64  <ef3f4a4cae2d387b874e53eec51b37aa> /System/Library/PrivateFrameworks/ChunkingLibrary.framework/ChunkingLibrary
0x18eb6c000 - 0x18eb6efff CommonAuth arm64  <b4d7e19fb01033aa9b536f36bc9e8132> /System/Library/PrivateFrameworks/CommonAuth.framework/CommonAuth
0x18eb70000 - 0x18eb82fff CommonUtilities arm64  <1cb495ce473a3127bb291cc541762fb3> /System/Library/PrivateFrameworks/CommonUtilities.framework/CommonUtilities
0x18eb84000 - 0x18eb88fff CommunicationsFilter arm64  <836ffdf2d1bf38948dc8ce6c2f8179e1> /System/Library/PrivateFrameworks/CommunicationsFilter.framework/CommunicationsFilter
0x18ec18000 - 0x18ec56fff ContentIndex arm64  <a2107dd376ac3e7da9261e74cec13881> /System/Library/PrivateFrameworks/ContentIndex.framework/ContentIndex
0x18ec58000 - 0x18ec5cfff CoreAUC arm64  <bf359bb9dcc837f78745ec21c2983ad2> /System/Library/PrivateFrameworks/CoreAUC.framework/CoreAUC
0x18ec90000 - 0x18ecf0fff CoreDAV arm64  <e5ff66c9ce4239f7a81436aca6cae6dd> /System/Library/PrivateFrameworks/CoreDAV.framework/CoreDAV
0x18ecf4000 - 0x18ed13fff CoreDuet arm64  <ee7872f60256383a96f35468fb7a3dc5> /System/Library/PrivateFrameworks/CoreDuet.framework/CoreDuet
0x18ed18000 - 0x18ed2afff CoreDuetDaemonProtocol arm64  <aa7ade578b203db19f39ea32a0e1829a> /System/Library/PrivateFrameworks/CoreDuetDaemonProtocol.framework/CoreDuetDaemonProtocol
0x18ed34000 - 0x18ed36fff CoreDuetDebugLogging arm64  <ec769c1bea803724880716f71249ba1c> /System/Library/PrivateFrameworks/CoreDuetDebugLogging.framework/CoreDuetDebugLogging
0x18eff4000 - 0x18f0a4fff CorePDF arm64  <cd828d67cd5a3f8f817e5578de264442> /System/Library/PrivateFrameworks/CorePDF.framework/CorePDF
0x18f118000 - 0x18f123fff CoreRecents arm64  <07ba243dfb6d3686849128707aaee229> /System/Library/PrivateFrameworks/CoreRecents.framework/CoreRecents
0x18f438000 - 0x18f4cafff CoreUI arm64  <01dbaf25ff893847ba41f2ff92b411a8> /System/Library/PrivateFrameworks/CoreUI.framework/CoreUI
0x18f4cc000 - 0x18f548fff CoreUtils arm64  <a30cc6baffe8324aaa50865c52d59141> /System/Library/PrivateFrameworks/CoreUtils.framework/CoreUtils
0x18f54c000 - 0x18f552fff CrashReporterSupport arm64  <ba2801fd567a305da540a0b276dc7537> /System/Library/PrivateFrameworks/CrashReporterSupport.framework/CrashReporterSupport
0x18f554000 - 0x18f55bfff DAAPKit arm64  <b631761d5d3c34e1a12ea2f07efa9055> /System/Library/PrivateFrameworks/DAAPKit.framework/DAAPKit
0x18f568000 - 0x18f5b7fff DataAccess arm64  <a3b77691efff37218b48737250d0d0e0> /System/Library/PrivateFrameworks/DataAccess.framework/DataAccess
0x18f814000 - 0x18f83afff DataAccessExpress arm64  <50d5ab9c38ee3e69bd4da116bc7bd4f8> /System/Library/PrivateFrameworks/DataAccessExpress.framework/DataAccessExpress
0x18f88c000 - 0x18f893fff DataMigration arm64  <e0c839ae4aed387887ea9853c6c25682> /System/Library/PrivateFrameworks/DataMigration.framework/DataMigration
0x18f89c000 - 0x18f89dfff DiagnosticLogCollection arm64  <fa41e1d5be703f8e80e8ff3316a49e3d> /System/Library/PrivateFrameworks/DiagnosticLogCollection.framework/DiagnosticLogCollection
0x18f8a0000 - 0x18f8c0fff DictionaryServices arm64  <d4d267ee319135ccb3a6679497243088> /System/Library/PrivateFrameworks/DictionaryServices.framework/DictionaryServices
0x18f8e8000 - 0x18f90efff EAP8021X arm64  <c99ae63150f83cd5b9dd00d12ac1e9f8> /System/Library/PrivateFrameworks/EAP8021X.framework/EAP8021X
0x18fa38000 - 0x18fa3afff FTClientServices arm64  <d5e1bea0e8b03ebd87218b42ccf8f1bf> /System/Library/PrivateFrameworks/FTClientServices.framework/FTClientServices
0x18fa3c000 - 0x18fa6efff FTServices arm64  <d918c6224d4830cd817a0bdacc0a2bd9> /System/Library/PrivateFrameworks/FTServices.framework/FTServices
0x18fa70000 - 0x18fe9dfff FaceCore arm64  <a0f71a06ddb83c77b3b59257e4002445> /System/Library/PrivateFrameworks/FaceCore.framework/FaceCore
0x18feb8000 - 0x18fec5fff FindMyDevice arm64  <6afd8c0fdacb3351980aecc33fa7dcd1> /System/Library/PrivateFrameworks/FindMyDevice.framework/FindMyDevice
0x18fed0000 - 0x18fed0fff FontServices arm64  <c7cd675f737e346db28b52c37065163f> /System/Library/PrivateFrameworks/FontServices.framework/FontServices
0x18fed4000 - 0x18ffb3fff libFontParser.dylib arm64  <48edcd60e46e3b9f9dffab1ae9283706> /System/Library/PrivateFrameworks/FontServices.framework/libFontParser.dylib
0x1900d0000 - 0x1900f0fff FrontBoardServices arm64  <17de7a3c55253f02a2d676919d73ccb6> /System/Library/PrivateFrameworks/FrontBoardServices.framework/FrontBoardServices
0x190828000 - 0x1908c7fff GameCenterFoundation arm64  <f7645ce42b8930f89e267a628596018c> /System/Library/PrivateFrameworks/GameCenterFoundation.framework/GameCenterFoundation
0x190978000 - 0x1909ccfff GameCenterUI arm64  <d642b3c38f8b3adea93602f64259fb51> /System/Library/PrivateFrameworks/GameCenterUI.framework/GameCenterUI
0x1909d0000 - 0x190b2efff AVConference arm64  <6f8bd1b176fc3f8b884a6bd2904fe1a8> /System/Library/PrivateFrameworks/GameKitServices.framework/Frameworks/AVConference.framework/AVConference
0x190b44000 - 0x190b6efff ICE arm64  <3e07c5b658fe3e6f8a1be0369ba8ff88> /System/Library/PrivateFrameworks/GameKitServices.framework/Frameworks/ICE.framework/ICE
0x190b70000 - 0x190b71fff LegacyHandle arm64  <0784b7db8ba838bf8e67dc33908f450f> /System/Library/PrivateFrameworks/GameKitServices.framework/Frameworks/LegacyHandle.framework/LegacyHandle
0x190b74000 - 0x190b7ffff SimpleKeyExchange arm64  <7f0e6d1869353bfb985c60f595324b6a> /System/Library/PrivateFrameworks/GameKitServices.framework/Frameworks/SimpleKeyExchange.framework/SimpleKeyExchange
0x190b80000 - 0x190b8dfff ViceroyTrace arm64  <ea938e6219f33c509cddca4ff3f99dd6> /System/Library/PrivateFrameworks/GameKitServices.framework/Frameworks/ViceroyTrace.framework/ViceroyTrace
0x190b90000 - 0x190b91fff snatmap arm64  <4a88d709154533d59b183ec61a507450> /System/Library/PrivateFrameworks/GameKitServices.framework/Frameworks/snatmap.framework/snatmap
0x190b94000 - 0x190c1bfff GameKitServices arm64  <f5f37ee4a2e43a06a24f05b2a18a6d89> /System/Library/PrivateFrameworks/GameKitServices.framework/GameKitServices
0x190c1c000 - 0x190c35fff GenerationalStorage arm64  <ef901d5502553db4992e914b9d6b9757> /System/Library/PrivateFrameworks/GenerationalStorage.framework/GenerationalStorage
0x190c38000 - 0x190ef2fff GeoServices arm64  <e20d801831213e1184e2af1442e7b197> /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
0x190ef4000 - 0x190f07fff GraphicsServices arm64  <b5078b39bd36372190e4ad5e7d991f68> /System/Library/PrivateFrameworks/GraphicsServices.framework/GraphicsServices
0x190fc0000 - 0x191028fff Heimdal arm64  <55335b3900963af28f5af19afd1bfab7> /System/Library/PrivateFrameworks/Heimdal.framework/Heimdal
0x1910e0000 - 0x191175fff HomeSharing arm64  <2deb2d5e54523701b2bda5371fc3180a> /System/Library/PrivateFrameworks/HomeSharing.framework/HomeSharing
0x1911e0000 - 0x191242fff IDS arm64  <c3ab13565e513311805a3813291b9c27> /System/Library/PrivateFrameworks/IDS.framework/IDS
0x191244000 - 0x191268fff IDSFoundation arm64  <5a05fb27e5083d09b5f289d7560edbee> /System/Library/PrivateFrameworks/IDSFoundation.framework/IDSFoundation
0x1912d8000 - 0x19139afff IMCore arm64  <44c45bd884f43998acc6e7bdbb57b39d> /System/Library/PrivateFrameworks/IMCore.framework/IMCore
0x191444000 - 0x1914b4fff IMFoundation arm64  <c8aa1eec15b63d05831678746a299da0> /System/Library/PrivateFrameworks/IMFoundation.framework/IMFoundation
0x1914c0000 - 0x1914c3fff IOAccelerator arm64  <ec8452ce495a3f1088b1c6024e027167> /System/Library/PrivateFrameworks/IOAccelerator.framework/IOAccelerator
0x1914c8000 - 0x1914cffff IOMobileFramebuffer arm64  <c1f736ec9ad732728480d64c59a86f5f> /System/Library/PrivateFrameworks/IOMobileFramebuffer.framework/IOMobileFramebuffer
0x1914d0000 - 0x1914d6fff IOSurface arm64  <719f179613ae37b688ee169eb5ed46fc> /System/Library/PrivateFrameworks/IOSurface.framework/IOSurface
0x1914d8000 - 0x1914dafff IOSurfaceAccelerator arm64  <3fb692bcaed8321db9c674cf00c5f719> /System/Library/PrivateFrameworks/IOSurfaceAccelerator.framework/IOSurfaceAccelerator
0x191594000 - 0x19159bfff IntlPreferences arm64  <1cba014916fa3c5f984e3a0c9f5bfb81> /System/Library/PrivateFrameworks/IntlPreferences.framework/IntlPreferences
0x19159c000 - 0x1915defff LanguageModeling arm64  <0f8255591fef33cdb8a91f460e678ccb> /System/Library/PrivateFrameworks/LanguageModeling.framework/LanguageModeling
0x19164c000 - 0x19165bfff LegacyGameKit arm64  <16bfba60bba83894aa2287bbbdeecbe3> /System/Library/PrivateFrameworks/LegacyGameKit.framework/LegacyGameKit
0x19166c000 - 0x1916b3fff MIME arm64  <a86fc4a77b8035428b8f6cc5ffb1d6e9> /System/Library/PrivateFrameworks/MIME.framework/MIME
0x191778000 - 0x191785fff MailServices arm64  <9072fc33768a3f569ea0bd79c8a7f3aa> /System/Library/PrivateFrameworks/MailServices.framework/MailServices
0x1917c8000 - 0x191886fff ManagedConfiguration arm64  <43215fab0090325d976c63af94aa02b5> /System/Library/PrivateFrameworks/ManagedConfiguration.framework/ManagedConfiguration
0x191894000 - 0x191895fff Marco arm64  <374e233c50c2373a8dc5ca0a817b12a4> /System/Library/PrivateFrameworks/Marco.framework/Marco
0x191898000 - 0x19191efff MediaControlSender arm64  <8042568e5afa3775a7b165d138a799ae> /System/Library/PrivateFrameworks/MediaControlSender.framework/MediaControlSender
0x1919d4000 - 0x1919e9fff MediaRemote arm64  <b54d94f44dcf3147ab669748e7fd1f19> /System/Library/PrivateFrameworks/MediaRemote.framework/MediaRemote
0x1919ec000 - 0x1919fdfff MediaServices arm64  <46469813721c3f6193bbd7fbb4e0a5eb> /System/Library/PrivateFrameworks/MediaServices.framework/MediaServices
0x191a20000 - 0x191a87fff IMAP arm64  <f68f50f855a6361c8518d56571167bd2> /System/Library/PrivateFrameworks/Message.framework/MailServices/IMAP.framework/IMAP
0x191a98000 - 0x191b94fff Message arm64  <982014080efb3ca187aa0cc993e9818d> /System/Library/PrivateFrameworks/Message.framework/Message
0x191ba0000 - 0x191ba3fff MessageSupport arm64  <1761532c47103f5092c043296744c01e> /System/Library/PrivateFrameworks/MessageSupport.framework/MessageSupport
0x191bb4000 - 0x191bc3fff MobileAsset arm64  <9164537c500e345abf5970138aa9b1dd> /System/Library/PrivateFrameworks/MobileAsset.framework/MobileAsset
0x191bc8000 - 0x191beefff MobileBackup arm64  <a58134b75c7033619ccf8c5a38f0ecb2> /System/Library/PrivateFrameworks/MobileBackup.framework/MobileBackup
0x191bf0000 - 0x191bfcfff MobileBluetooth arm64  <d698ec87311e3132b0de7ce0ddcd8fbb> /System/Library/PrivateFrameworks/MobileBluetooth.framework/MobileBluetooth
0x191c10000 - 0x191c22fff MobileDeviceLink arm64  <63cf34f0d0443a5b90209232e9987232> /System/Library/PrivateFrameworks/MobileDeviceLink.framework/MobileDeviceLink
0x191c24000 - 0x191c2dfff MobileIcons arm64  <cd577ec393b537bbab28fe4f672f4fe7> /System/Library/PrivateFrameworks/MobileIcons.framework/MobileIcons
0x191c30000 - 0x191c39fff MobileInstallation arm64  <6a17b4f0b6aa363ba2decf9b6c8167b1> /System/Library/PrivateFrameworks/MobileInstallation.framework/MobileInstallation
0x191c3c000 - 0x191c4bfff MobileKeyBag arm64  <77b5fa7d33ef319299072ec85128fe37> /System/Library/PrivateFrameworks/MobileKeyBag.framework/MobileKeyBag
0x191c88000 - 0x191c8bfff MobileSystemServices arm64  <9b2bbc93fbb231baa08b41c6aee209ed> /System/Library/PrivateFrameworks/MobileSystemServices.framework/MobileSystemServices
0x191cb4000 - 0x191cc5fff MobileWiFi arm64  <79c784a6040b35d1b09e97c60b0def58> /System/Library/PrivateFrameworks/MobileWiFi.framework/MobileWiFi
0x191d14000 - 0x191eeffff MusicLibrary arm64  <53fbcc46dafd3634b696a9f9878c8f4f> /System/Library/PrivateFrameworks/MusicLibrary.framework/MusicLibrary
0x191fa4000 - 0x191faafff Netrb arm64  <b58a090c9a12346a9f4af0d22626f6f3> /System/Library/PrivateFrameworks/Netrb.framework/Netrb
0x191fac000 - 0x191fb3fff NetworkStatistics arm64  <8d818200ba99385bbd69dad9dda0319d> /System/Library/PrivateFrameworks/NetworkStatistics.framework/NetworkStatistics
0x191fb4000 - 0x191fd6fff Notes arm64  <698d570fbdb9362195fdb66aacfaf2d2> /System/Library/PrivateFrameworks/Notes.framework/Notes
0x191fe0000 - 0x191fe3fff OAuth arm64  <3049cf937f053793a4b97aa26375f1cb> /System/Library/PrivateFrameworks/OAuth.framework/OAuth
0x1927b8000 - 0x192806fff OpenCL arm64  <7350f5063e4232a1a3cc921e47de6ef5> /System/Library/PrivateFrameworks/OpenCL.framework/OpenCL
0x192924000 - 0x19294cfff PersistentConnection arm64  <b7044531bbf73fcf9b586269283bfb50> /System/Library/PrivateFrameworks/PersistentConnection.framework/PersistentConnection
0x192d94000 - 0x192de1fff PhysicsKit arm64  <625733e02bc3372ca473ac973020e32e> /System/Library/PrivateFrameworks/PhysicsKit.framework/PhysicsKit
0x192de4000 - 0x192dfefff PlugInKit arm64  <cc8ba22bd61e32a5a80b083d5e0dd86e> /System/Library/PrivateFrameworks/PlugInKit.framework/PlugInKit
0x192e00000 - 0x192e08fff PowerLog arm64  <506bca8a5af033a68bbd5958c9f995a7> /System/Library/PrivateFrameworks/PowerLog.framework/PowerLog
0x19305c000 - 0x19311bfff Preferences arm64  <55e92e1b45f5350db713977fadcbecf4> /System/Library/PrivateFrameworks/Preferences.framework/Preferences
0x19311c000 - 0x193163fff PrintKit arm64  <2181399ad0d331e8934c69d4220f7bcc> /System/Library/PrivateFrameworks/PrintKit.framework/PrintKit
0x193168000 - 0x193227fff ProofReader arm64  <377a2b68fdcf3fe3be30455084083eb5> /System/Library/PrivateFrameworks/ProofReader.framework/ProofReader
0x19323c000 - 0x19324afff ProtocolBuffer arm64  <0a4f092c935c3f5291152d30a2e9e008> /System/Library/PrivateFrameworks/ProtocolBuffer.framework/ProtocolBuffer
0x193288000 - 0x193306fff Quagga arm64  <a0e7e7857a69346ab1f5c4e065491469> /System/Library/PrivateFrameworks/Quagga.framework/Quagga
0x1934a0000 - 0x1934e3fff RemoteUI arm64  <64ef0d3073fe37ada8f530cfe3e92848> /System/Library/PrivateFrameworks/RemoteUI.framework/RemoteUI
0x193564000 - 0x193605fff SAObjects arm64  <7597eb6e1e253ddbbd70edf507e61315> /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
0x193834000 - 0x193853fff SpringBoardServices arm64  <118627bb068a3a82b87ba8c62583e7a8> /System/Library/PrivateFrameworks/SpringBoardServices.framework/SpringBoardServices
0x193c48000 - 0x193d8ffff StoreServices arm64  <8c5dfc1c4baf3eaca6420c6af360bf5e> /System/Library/PrivateFrameworks/StoreServices.framework/StoreServices
0x193e80000 - 0x193e83fff TCC arm64  <0dc32625c39b3087893e5da6ff7dd7b4> /System/Library/PrivateFrameworks/TCC.framework/TCC
0x193ed4000 - 0x193f17fff TelephonyUtilities arm64  <1cb4e1e61c2e3d5580283cd1e3039be4> /System/Library/PrivateFrameworks/TelephonyUtilities.framework/TelephonyUtilities
0x194cf8000 - 0x194d26fff TextInput arm64  <b19843fb56343a97b9e0dd0014231115> /System/Library/PrivateFrameworks/TextInput.framework/TextInput
0x194dfc000 - 0x194ed5fff UIFoundation arm64  <402e5079593a32a8b49d604f4a1eedeb> /System/Library/PrivateFrameworks/UIFoundation.framework/UIFoundation
0x194efc000 - 0x194efffff UserFS arm64  <da16ebc138783ad7a4a1ed8d0b09bda7> /System/Library/PrivateFrameworks/UserFS.framework/UserFS
0x1954dc000 - 0x195628fff VideoProcessing arm64  <770f4a0a553430c683541e88a9121d96> /System/Library/PrivateFrameworks/VideoProcessing.framework/VideoProcessing
0x195750000 - 0x195774fff VoiceServices arm64  <116b6fde28453423bd2983d14170dbb3> /System/Library/PrivateFrameworks/VoiceServices.framework/VoiceServices
0x195818000 - 0x195840fff WebBookmarks arm64  <fb8394570493371c850cdde82c85969d> /System/Library/PrivateFrameworks/WebBookmarks.framework/WebBookmarks
0x195860000 - 0x196787fff WebCore arm64  <42110cbe7d7e3f899dc1bd4015282fcc> /System/Library/PrivateFrameworks/WebCore.framework/WebCore
0x196788000 - 0x19685afff WebKitLegacy arm64  <23c78a31ba4b39cd9286e376281b0e66> /System/Library/PrivateFrameworks/WebKitLegacy.framework/WebKitLegacy
0x1969e8000 - 0x1969e8fff WirelessCoexManager arm64  <4b6a1818830133eeb518e0cc4a42b272> /System/Library/PrivateFrameworks/WirelessCoexManager.framework/WirelessCoexManager
0x1969ec000 - 0x196a0ffff WirelessDiagnostics arm64  <efd4e0f65d6d32b9a2b35fe8e77116c7> /System/Library/PrivateFrameworks/WirelessDiagnostics.framework/WirelessDiagnostics
0x196a30000 - 0x196a39fff XPCObjects arm64  <9eb286c27f9333be9f8ed58c733abd7b> /System/Library/PrivateFrameworks/XPCObjects.framework/XPCObjects
0x196c6c000 - 0x196c96fff iCalendar arm64  <36f60138b79e3dada1c790ff60bb86e0> /System/Library/PrivateFrameworks/iCalendar.framework/iCalendar
0x196cc4000 - 0x196d06fff iTunesStore arm64  <76f474c7ddfc3ba1a0cd1218312af163> /System/Library/PrivateFrameworks/iTunesStore.framework/iTunesStore
0x197368000 - 0x197378fff libAWDProtobufFacetimeiMessage.dylib arm64  <16bd5f4b9b3e3ff6a561062a3808b2a3> /usr/lib/libAWDProtobufFacetimeiMessage.dylib
0x19747c000 - 0x197482fff libAWDSupportConfig.dylib arm64  <858dcb604ef8351ea589ee7f58fb2bc6> /usr/lib/libAWDSupportConfig.dylib
0x197484000 - 0x1975c9fff libAWDSupportFramework.dylib arm64  <19ab591a9fe03d01bd1cb60adc3cee6e> /usr/lib/libAWDSupportFramework.dylib
0x1975cc000 - 0x1975cdfff libAWDSupportInfo.dylib arm64  <9a2f9c0053753191b22d2ad8a97f8a85> /usr/lib/libAWDSupportInfo.dylib
0x1975dc000 - 0x1975e5fff libAccessibility.dylib arm64  <aa09cdc041b53a05b0161253d121621d> /usr/lib/libAccessibility.dylib
0x197878000 - 0x197893fff libCRFSuite.dylib arm64  <a41a2f95f1ff30d9a4ab2d6145480db2> /usr/lib/libCRFSuite.dylib
0x1978d4000 - 0x197a0bfff libFosl_dynamic.dylib arm64  <3013ac9596c03e458767997983ac758f> /usr/lib/libFosl_dynamic.dylib
0x197a30000 - 0x197a4afff libMobileGestalt.dylib arm64  <f625ec0e13bf3a2f8ba8571b9546444d> /usr/lib/libMobileGestalt.dylib
0x197a7c000 - 0x197a7dfff libSystem.B.dylib arm64  <882b19bba06d348d97fcdaf545163f47> /usr/lib/libSystem.B.dylib
0x197b00000 - 0x197b4efff libTelephonyUtilDynamic.dylib arm64  <a84c6f652ea63a52921b96b6185c531c> /usr/lib/libTelephonyUtilDynamic.dylib
0x197c78000 - 0x197ca2fff libarchive.2.dylib arm64  <6e7ce417e487309c8acc744b1b6b523f> /usr/lib/libarchive.2.dylib
0x197ca4000 - 0x197ca4fff libassertion_extension.dylib arm64  <9d3b3adf5dde3ecb9a438a367d5b85d1> /usr/lib/libassertion_extension.dylib
0x197ce4000 - 0x197cf4fff libbsm.0.dylib arm64  <6651c9abc7b6353c8343d7f0f4e09a23> /usr/lib/libbsm.0.dylib
0x197cf8000 - 0x197d08fff libbz2.1.0.dylib arm64  <f6ec1b6a4719369aa059ee3269823a2d> /usr/lib/libbz2.1.0.dylib
0x197d0c000 - 0x197d62fff libc++.1.dylib arm64  <c8e65982941e374c95463384e600181d> /usr/lib/libc++.1.dylib
0x197d64000 - 0x197d86fff libc++abi.dylib arm64  <fd49f85cb61d31b582895366ea6c2d01> /usr/lib/libc++abi.dylib
0x197d8c000 - 0x197d9dfff libcmph.dylib arm64  <dca2c6c0bd65352b947d537395e23ab9> /usr/lib/libcmph.dylib
0x197de4000 - 0x197e00fff libextension.dylib arm64  <e8ead22587533875b26071dda1330ce1> /usr/lib/libextension.dylib
0x197e30000 - 0x197e35fff libheimdal-asn1.dylib arm64  <b90901b2ba0338b484b8b447b82293fa> /usr/lib/libheimdal-asn1.dylib
0x197e38000 - 0x197f2bfff libiconv.2.dylib arm64  <3ebb30c258f43c0294bcdeebb48b3fc1> /usr/lib/libiconv.2.dylib
0x197f2c000 - 0x198113fff libicucore.A.dylib arm64  <02e9eb5b92473df89af04da09371417a> /usr/lib/libicucore.A.dylib
0x198128000 - 0x198129fff liblangid.dylib arm64  <80e626200785352a8d5e98a061ca19b8> /usr/lib/liblangid.dylib
0x19812c000 - 0x198138fff liblockdown.dylib arm64  <f53a3d2ac76330f7bd299be0a9206109> /usr/lib/liblockdown.dylib
0x19813c000 - 0x198155fff liblzma.5.dylib arm64  <ac6807960fbd34d9939a070cf6ecf081> /usr/lib/liblzma.5.dylib
0x19852c000 - 0x198543fff libmis.dylib arm64  <130d691e68403ec2882abd44479e9891> /usr/lib/libmis.dylib
0x198578000 - 0x198774fff libobjc.A.dylib arm64  <e6224d745a023588af8e5bb67498139a> /usr/lib/libobjc.A.dylib
0x1987f0000 - 0x198859fff libprotobuf.dylib arm64  <836e780892373db08dd29031315414ec> /usr/lib/libprotobuf.dylib
0x19885c000 - 0x198879fff libresolv.9.dylib arm64  <fd78cddab3e43bd9a7a6440273b15059> /usr/lib/libresolv.9.dylib
0x1988ac000 - 0x19897dfff libsqlite3.dylib arm64  <286839512b673f7c938aa79ac70bde15> /usr/lib/libsqlite3.dylib
0x198980000 - 0x1989d2fff libstdc++.6.dylib arm64  <fc1f30ba249639148b4ab9efa739e574> /usr/lib/libstdc++.6.dylib
0x1989d4000 - 0x198a06fff libtidy.A.dylib arm64  <2b69233bafd53bdaafa6d9b1767bbad5> /usr/lib/libtidy.A.dylib
0x198a08000 - 0x198a11fff libtzupdate.dylib arm64  <f4e015552f4e354baae69d67893d8669> /usr/lib/libtzupdate.dylib
0x198a18000 - 0x198b06fff libxml2.2.dylib arm64  <dbcfe4d423bb3ae48174394f298ad244> /usr/lib/libxml2.2.dylib
0x198b08000 - 0x198b31fff libxslt.1.dylib arm64  <f3770c5f8ac3313bbe4ef1258ebf5733> /usr/lib/libxslt.1.dylib
0x198b34000 - 0x198b45fff libz.1.dylib arm64  <2a347410b967358289e8256c913714de> /usr/lib/libz.1.dylib
0x198b48000 - 0x198b4cfff libcache.dylib arm64  <d322f485769b3fd5a11bc2aff7265fdf> /usr/lib/system/libcache.dylib
0x198b50000 - 0x198b5cfff libcommonCrypto.dylib arm64  <2aa56db3851c3b24b7eb849f0e289140> /usr/lib/system/libcommonCrypto.dylib
0x198b60000 - 0x198b63fff libcompiler_rt.dylib arm64  <65f2a15e126435769154e2a7b44b942e> /usr/lib/system/libcompiler_rt.dylib
0x198b64000 - 0x198b6bfff libcopyfile.dylib arm64  <1f428d2df193398e9e72250952f08953> /usr/lib/system/libcopyfile.dylib
0x198b6c000 - 0x198bc1fff libcorecrypto.dylib arm64  <4a97f227130a3cbaa0a8c5b561e97314> /usr/lib/system/libcorecrypto.dylib
0x198bc4000 - 0x198beafff libdispatch.dylib arm64  <e19d74563485344485b6d4457a93e89d> /usr/lib/system/libdispatch.dylib
0x198bec000 - 0x198beefff libdyld.dylib arm64  <d5ebc6da536338f5be9bb4c3be2f7716> /usr/lib/system/libdyld.dylib
0x198bf0000 - 0x198bf0fff liblaunch.dylib arm64  <da357dcde300321685d77140a4f82e6c> /usr/lib/system/liblaunch.dylib
0x198bf4000 - 0x198bf9fff libmacho.dylib arm64  <cddfd20412643baeb9023095eb2cf29f> /usr/lib/system/libmacho.dylib
0x198bfc000 - 0x198bfdfff libremovefile.dylib arm64  <e8124da88b1131f2ac005b75d8559ca7> /usr/lib/system/libremovefile.dylib
0x198c00000 - 0x198c15fff libsystem_asl.dylib arm64  <17448aec6f7d3498aebcabc8a1598c9a> /usr/lib/system/libsystem_asl.dylib
0x198c18000 - 0x198c19fff libsystem_blocks.dylib arm64  <f38b7145bed330d98d8d79b8362b03de> /usr/lib/system/libsystem_blocks.dylib
0x198c1c000 - 0x198c9cfff libsystem_c.dylib arm64  <71df87643ff839bdb9559e4e50bb6eea> /usr/lib/system/libsystem_c.dylib
0x198ca0000 - 0x198ca2fff libsystem_configuration.dylib arm64  <37655cc87bb3391b946955b0fbc4384a> /usr/lib/system/libsystem_configuration.dylib
0x198ca4000 - 0x198ca5fff libsystem_coreservices.dylib arm64  <a8e2019df4123295bf71800fa1bd73be> /usr/lib/system/libsystem_coreservices.dylib
0x198ca8000 - 0x198cb8fff libsystem_coretls.dylib arm64  <e837369c4d623fc7adb19a892b03aba8> /usr/lib/system/libsystem_coretls.dylib
0x198cbc000 - 0x198cc4fff libsystem_dnssd.dylib arm64  <18b39491d06c3fa18c810118f03143ee> /usr/lib/system/libsystem_dnssd.dylib
0x198cc8000 - 0x198ce9fff libsystem_info.dylib arm64  <72514f76b03335729f18da536331df97> /usr/lib/system/libsystem_info.dylib
0x198cec000 - 0x198d0cfff libsystem_kernel.dylib arm64  <ccacc11311c23f8f8fa58f58ce96be0f> /usr/lib/system/libsystem_kernel.dylib
0x198d10000 - 0x198d2cfff libsystem_m.dylib arm64  <e25dbaa110a03706a8ea7e0709ec385a> /usr/lib/system/libsystem_m.dylib
0x198d30000 - 0x198d49fff libsystem_malloc.dylib arm64  <bb0250acb085340ea6689a755edc5515> /usr/lib/system/libsystem_malloc.dylib
0x198d4c000 - 0x198d83fff libsystem_network.dylib arm64  <d7b99c2b98ff3affbe5a8743121419d2> /usr/lib/system/libsystem_network.dylib
0x198d84000 - 0x198d8afff libsystem_networkextension.dylib arm64  <8248d7bdf0bd3e0b9d2a5ba10b238921> /usr/lib/system/libsystem_networkextension.dylib
0x198d8c000 - 0x198d96fff libsystem_notify.dylib arm64  <4a9bcea2df8d351f987d0e9f84406427> /usr/lib/system/libsystem_notify.dylib
0x198d98000 - 0x198d9cfff libsystem_platform.dylib arm64  <03902be9733b35d2b193cf8724a8d95a> /usr/lib/system/libsystem_platform.dylib
0x198da0000 - 0x198da8fff libsystem_pthread.dylib arm64  <ffbb6452a3e531969e9571cd95896210> /usr/lib/system/libsystem_pthread.dylib
0x198dac000 - 0x198daefff libsystem_sandbox.dylib arm64  <b8d755b4fc043ad791277d6a8cf0b4b6> /usr/lib/system/libsystem_sandbox.dylib
0x198db0000 - 0x198db3fff libsystem_stats.dylib arm64  <e2b3982965873f27b542a1a81f212b5b> /usr/lib/system/libsystem_stats.dylib
0x198db4000 - 0x198dbafff libsystem_trace.dylib arm64  <122df0fd03b43a8f82ed69916c95524a> /usr/lib/system/libsystem_trace.dylib
0x198dbc000 - 0x198dc1fff libunwind.dylib arm64  <0c07617876a43cacbde6104a2b75f4f2> /usr/lib/system/libunwind.dylib
0x198dc4000 - 0x198de7fff libxpc.dylib arm64  <2a02e77c431732e292fbe37af8747b2e> /usr/lib/system/libxpc.dylib
</code></pre>

**Comment by titovmaxim** [comment]
P.S. The bug it quite important. libGDX 64 bits builds don't work at all because of it (logging is enabled by default during initialization step).

P.P.S. The crash occurs only on the device, simulator works just fine.

**Comment by ntherning** [comment]
Could be related to #742. I'm currently working on a fix for that one in #754.

**Comment by ntherning** [comment]
This is due to variadic functions (like `NSLog()`) and parameter passing on ARM64 being done quite different compared to ordinary functions.

**Comment by ntherning** [comment]
#762 has been fixed and `Foundation.log()` should now work as expected on ARM64. Please try with the next nightly or next release.

**Comment by jonpricelegend** [comment]
How do I fetch the latest snapshot? I'm still getting beta-03 jars despite having SNAPSHOT defined in build.gradle, arm64 is still crashing on device.
```
admin$ ls -R .gradle | grep robovm-rt
robovm-rt
.gradle/caches/modules-2/files-2.1/org.robovm/robovm-rt:
.gradle/caches/modules-2/files-2.1/org.robovm/robovm-rt/1.0.0-SNAPSHOT:
.gradle/caches/modules-2/files-2.1/org.robovm/robovm-rt/1.0.0-SNAPSHOT/ac6df530a460f81b2844b4e8669c57e46f984c33:
robovm-rt-1.0.0-SNAPSHOT.pom
.gradle/caches/modules-2/files-2.1/org.robovm/robovm-rt/1.0.0-beta-03:
.gradle/caches/modules-2/files-2.1/org.robovm/robovm-rt/1.0.0-beta-03/ac60c382ae880d311a91bc6aa745e809c02ad28f:
robovm-rt-1.0.0-beta-03.jar
.gradle/caches/modules-2/files-2.1/org.robovm/robovm-rt/1.0.0-beta-03/d33d0c0f69973b5245134c38ecfd42776ac9ce48:
robovm-rt-1.0.0-beta-03.pom
.gradle/caches/modules-2/files-2.1/org.robovm/robovm-rt/1.0.0-beta-03/e8f5216f12873608694056195399b464ca07d917:
robovm-rt-1.0.0-beta-03-sources.jar
robovm-rt
.gradle/caches/modules-2/metadata-2.14/descriptors/org.robovm/robovm-rt:
.gradle/caches/modules-2/metadata-2.14/descriptors/org.robovm/robovm-rt/1.0.0-SNAPSHOT:
.gradle/caches/modules-2/metadata-2.14/descriptors/org.robovm/robovm-rt/1.0.0-SNAPSHOT/f19473150cef4fb4c272143e5a6441e5:
.gradle/caches/modules-2/metadata-2.14/descriptors/org.robovm/robovm-rt/1.0.0-beta-03:
.gradle/caches/modules-2/metadata-2.14/descriptors/org.robovm/robovm-rt/1.0.0-beta-03/4471c3b2f5ea2d40ffaa8b3948cdbacd:
```
build.gradle:
```
buildscript {
    repositories {
        mavenCentral()
        maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
    }
    dependencies {
        classpath 'org.robovm:robovm-gradle-plugin:1.0.0-SNAPSHOT'
    }
}

allprojects {
    repositories {
        mavenCentral()
        maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
    }

    apply plugin: "eclipse"
    apply plugin: "idea"

    version = '1.0'
    ext {
        appName = 'test'
        gdxVersion = '1.5.4-SNAPSHOT'
        roboVMVersion = '1.0.0-SNAPSHOT'
        box2DLightsVersion = '1.3'
        ashleyVersion = '1.3.1'
        aiVersion = '1.4.0'
    }
}

project(":ios") {
    apply plugin: "java"
    apply plugin: "robovm"

    configurations { natives }

    dependencies {
        compile project(":core")
        compile fileTree(dir: 'libs', include: '*.jar')
        compile "org.robovm:robovm-rt:${roboVMVersion}"
        compile "org.robovm:robovm-cocoatouch:${roboVMVersion}"
        compile "com.badlogicgames.gdx:gdx-backend-robovm:$gdxVersion"
        natives "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-ios"
        natives "com.badlogicgames.gdx:gdx-freetype-platform:$gdxVersion:natives-ios"
    }
}
```

Crash log:
```
Hardware Model:      iPad4,7
...
Code Type:           ARM-64 (Native)
...
Exception Type:  EXC_CRASH (SIGSEGV)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Triggered by Thread:  1
...
Thread 1 name:  Dispatch queue: com.apple.libdispatch-manager
Thread 1 Crashed:
0   libsystem_kernel.dylib        	0x00000001966f0c94 0x1966f0000 + 3220
1   libdispatch.dylib             	0x00000001965d897c 0x1965c8000 + 67964
2   libdispatch.dylib             	0x00000001965cb3b0 0x1965c8000 + 13232

Thread 2:
...
Thread 1 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000004   x1: 0x0000000000000000   x2: 0x0000000000000000   x3: 0x0000000101f975d0
    x4: 0x0000000000000001   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x0000000000000000
    x8: 0x0000000000000000   x9: 0x0000000000000000  x10: 0x0000000101ee8000  x11: 0x00000000005c098a
   x12: 0x000000000000ffee  x13: 0x000000000000fff2  x14: 0x0000000000000000  x15: 0x0000000126d06200
   x16: 0x0000000000000171  x17: 0x0000000000000000  x18: 0x0000000000000000  x19: 0x0000000101f97600
   x20: 0x0000000101f975d0  x21: 0x000000019a2ecbc0  x22: 0x000000019a2ec800  x23: 0x00000001965ed3a8
   x24: 0x000000019a2ec840  x25: 0x0000000101f980e0  x26: 0x0000000000000000  x27: 0x000000019a2ec918
   x28: 0x000000019a2ec910  fp: 0x0000000101f97640   lr: 0x00000001965d8980
    sp: 0x0000000101f975d0   pc: 0x00000001966f0c94 cpsr: 0x60000000
```

**Comment by badlogic** [comment]
Clear your Gradle cache (~/.gradle, $project/.gradle), then either build on
the CLI or refresh the dependencies by selecting all your projects in
Eclipse, then right click, Gradle -> Refresh All Dependencies.

That being said, libGDX 1.5.4-SNAPSHOT's RoboVM backend depends on RoboVM
1.0.0-beta3 explicitely. Gradle may not be smart enough to pick the RoboVM
SNAPSHOT dependencies you explicitely define in your build.gradle.

**Comment by Peter-Warlock** [comment]
I'm having the same issue on iPhone5s. (libGDX 1.5.4 and roboVM 1.0.0-beta-04)
Is there a version without this bug?
