### ISSUE TITLE
nightly builds (snapshots) can't build Java 8 lambdas

### ISSUE THREAD

**Issue by magicgoose** [robovm/robovm#950]
Latest stable release does handle lambdas without problems, but nightly builds fail to build iOS applications with lambdas.

Given that I'm sometimes forced to use nightly builds because of https://github.com/robovm/robovm/issues/940, this is annoying :disappointed:

**Comment by BlueRiverInteractive** [comment]
Related: https://github.com/robovm/robovm/issues/922

**Comment by ntherning** [comment]
Yeah, this has now been fixed in #922.

**Comment by magicgoose** [comment]
In the current nightly build the problem is still there.
(`org.robovm.idea-1.1.1-SNAPSHOT-plugin-dist-20150504_021139-63.jar`)
